sheet:
  id: "PUT_GOOGLE_SHEET_ID"
  timeline_tab: "Timeline"
  batch_ms: 750
google_auth:
  credentials_json: "./credentials.json"
midi:
  watch_dir: "D:/DAWSheet/in"
  allowed_exts: [".mid", ".lrc", ".vtt"]
  ignore_partial: true
  debounce_ms: 600
  stable_checks: 3
  assume_min_event_beats: 0.5
  default_tail_beats: 4
  merge_subbeat_blips: true
asr:
  enable_realtime: true
  device: "auto"
  model: "medium"
  input_source: "loopback"
  latency_comp_ms: 250
offline_align:
  enable: true
  tool: "whisperx"
sections:
  ngram_bars: 8
  chorus_weight: 1.0
  lyric_repeat_weight: 0.7
export:
  out_dir: "./exports"
  write_lrc: true
  write_vtt: true
  write_json: true
  write_csv: true
  write_midi_markers: true
project:
  id_prefix: "CFY"
