name: Playback Jobs CI

on:
  push:
    branches: [feat/playback-jobs-persistence]
  pull_request:
    branches: [main]

jobs:
  java-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Run Gradle tests (proxy-java)
        working-directory: apps/proxy-java
        run: |
          ./gradlew.bat test --console=plain || ./gradlew test --console=plain

  python-tests:
    runs-on: ubuntu-latest
    needs: java-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run pytest
        run: |
          pytest -q
